"""add rate_limit_events table (P3 PY-8)

Revision ID: ab7adf33a41f
Revises: 53601a8643b7
Create Date: 2026-06-21 21:39:39.821473

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ab7adf33a41f'
down_revision: Union[str, Sequence[str], None] = '53601a8643b7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
